name = "Existence SMP: Project Create 2"
author = "Mallory"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eef021428e29bd9e12eba6aa6b6daa2b484acfba074ec58ca7de74d520407ea0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
