name = "Existence SMP: Project Create 2"
author = "Mallory"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c31849defadcecd4021294366f141bb93ea58e52995cf8294e7f3ae6c648c14b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
