name = "Existence SMP: Project Create 2"
author = "Mallory"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f13ac1185e88a23220ecb936663c144a60e33153179680e69693883adad9931f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
