[flavor_groups.world_map_mod]
name = "World Map Mod"
description = "Which world map mod you'd like to use."
side = "client"
[[flavor_groups.world_map_mod.choices]]
id = "no_world_map"
name = "None"
description = "Bring your own world map mod, or use none at all."
[[flavor_groups.world_map_mod.choices]]
id = "xaeros_world_map"
name = "Xaero's World Map"
description = "Adds a full screen world map which shows you what you have explored in the world. Works great together with Xaero's Minimap."

[flavor_groups.minimap_mod]
name = "Minimap Mod"
description = "Which minimap mod you'd like to use."
side = "client"
[[flavor_groups.minimap_mod.choices]]
id = "no_minimap"
name = "None"
description = "Bring your own minimap mod, or use none at all."
[[flavor_groups.minimap_mod.choices]]
id = "xaeros_minimap"
name = "Xaero's Minimap"
description = "Displays a map of the nearby world terrain, players, mobs, entities in the corner of your screen. Lets you create waypoints which help you find the locations you've marked."

[metafile.xaeros-world-map]
flavors = ["xaeros_world_map"]
[metafile.xaeros-minimap]
flavors = ["xaeros_minimap"]